name = "personal-website"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"  # Removed npm install as it's done automatically
output_dir = ".next"       # For Next.js output

[site]
bucket = ".next/static"    # For Next.js static assets

[build.upload]
format = "service-worker"  # Better for Next.js applications

# Optional: Add environment-specific configurations
[env.production]
vars = { NODE_ENV = "production" }

[env.development]
vars = { NODE_ENV = "development" }