[build]
command = "npm install && npm run build"  # Changed to run npm install first

[build.upload]
format = "directory"

[site]  # Changed from [pages]
bucket = ".vercel/output/static"  # Changed property name